CREATE TABLE IF NOT EXISTS USERS
(
    id       VARCHAR(36) PRIMARY KEY,
    username VARCHAR(15) NOT NULL,
    password VARCHAR(60) NOT NULL
);
CREATE TABLE IF NOT EXISTS ROLE
(
    id   VARCHAR(36) PRIMARY KEY,
    role VARCHAR(20) NOT NULL
);
CREATE TABLE IF NOT EXISTS ROLE_FOR_USER
(
    user_id VARCHAR(36) NOT NULL REFERENCES USERS(id) ON DELETE CASCADE,
    role_id VARCHAR(36) NOT NULL REFERENCES ROLE(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT "role_for_user_fk_1" FOREIGN KEY (user_id) REFERENCES USERS (id),
    CONSTRAINT "role_for_user_fk_2" FOREIGN KEY (role_id) REFERENCES ROLE (id)
)