CREATE TABLE IF NOT EXISTS MESSAGES
(
    id       VARCHAR(36) PRIMARY KEY,
    message VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS MESSAGES_FROM_USER
(
    message_id VARCHAR(36) NOT NULL REFERENCES MESSAGES (id) ON DELETE CASCADE,
    user_id    VARCHAR(36) NOT NULL REFERENCES USERS (id) ON DELETE CASCADE,
    PRIMARY KEY (message_id, user_id),
    CONSTRAINT "messages_from_user_fk_1" FOREIGN KEY (message_id) REFERENCES MESSAGES (id),
    CONSTRAINT "messages_from_user_fk_2" FOREIGN KEY (user_id) REFERENCES USERS (id)
)